[project]
name = "contracts-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MatthiasUckert", email = "matthias.uckert@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.4.1",
    "en-core-web-lg",
    "en-core-web-md",
    "en-core-web-sm",
    "en-core-web-trf",
    "ipykernel>=7.2.0",
    "pandas>=3.0.3",
    "pandas-stubs~=3.0.3",
    "pyarrow>=24.0.0",
    "spacy[transformers]>=3.8.14",
]

[project.scripts]
contracts-engine = "contracts_engine:main"

[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
en-core-web-md = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl" }
en-core-web-lg = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl" }
en-core-web-trf = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl" }
